project:
  type: website

website:
  title: "Juho Timonen"
  site-url: https://jtimonen.github.io
  description: "Juho Timonen's personal website"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: blog.qmd
        text: Blog
        icon: bookmark
      - href: publications.qmd
        text: Publications
        icon: book
      - href: software.qmd
        text: Software
        icon: body-text

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



