project:
  type: website

website:
  title: "Juho Timonen"
  site-url: https://jtimonen.github.io
  description: "Juho Timonen's personal website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



