project:
  type: website

website:
  title: "Juho Timonen"
  site-url: https://jtimonen.github.io
  favicon: images/icon.png
  description: "Juho Timonen's personal website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: blog.qmd
        text: Posts
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: projects.qmd
        text: Hobby projects

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    number-sections: true



